location files ccreated
douglaskline/trucktrackrepo pull request #169
Opened 2022-02-15 21:27 UTC by nischalsaladi

created location
closes issue 117

2022-02-15 21:32 UTC, douglaskline requested changes
please remove code pertaining to project 4
only leave code that addresses this issue

2022-02-15 21:37 UTC, caelinquigley approved these changes

2022-02-15 22:01 UTC, nischalsaladi commented
> please remove code pertaining to project 4 only leave code that addresses this issue

Hey!
I've updated the files for you to review it.

2022-02-16 18:37 UTC, douglaskline approved these changes

2022-02-16 18:46 UTC, merged