changes made to line 3
douglaskline/trucktrackrepo pull request #357
Opened 2022-03-26 20:15 UTC by hvanderhoof

2022-03-26 20:21 UTC, hvanderhoof commented
@douglaskline I'm not seeing anywhere that it is telling me that I have a conflict between branch A and branch B

2022-03-27 04:32 UTC, ethancook6151 approved these changes

2022-04-07 17:25 UTC, douglaskline requested changes
@hvanderhoof you still need to resolve the conflicts

2022-04-12 18:52 UTC, douglaskline approved these changes

2022-04-12 18:52 UTC, merged