Issue 261 seed the database with wilmington food trucks
douglaskline/trucktrackrepo pull request #400
Opened 2022-04-06 23:52 UTC by AysunKaramustafaoglu

2022-04-06 23:53 UTC, AysunKaramustafaoglu commented
@nischalsaladi @douglaskline i need approvals please

2022-04-07 19:08 UTC, douglaskline requested changes
please fix some of the syntax

2022-04-07 20:36 UTC, douglaskline approved these changes

2022-04-07 20:36 UTC, douglaskline approved these changes

2022-04-07 20:38 UTC, dupreejames13 approved these changes
looks good :)

2022-04-07 20:41 UTC, merged