Project 14 Changes
douglaskline/trucktrackrepo pull request #429
Opened 2022-04-12 17:35 UTC by Chrishensley98

Closes #428

2022-04-12 18:42 UTC, yopinq approved these changes
Looks good. Closes #428

2022-04-12 19:17 UTC, douglaskline requested changes
@Chrishensley98 
you need to move your test inside the curly braces so it's with the other tests
you'll also need to add the [Fact] annotation at the top

2022-04-13 19:40 UTC, AubreyBordeaux approved these changes
changes look good

2022-04-28 15:41 UTC, douglaskline approved these changes

2022-05-04 14:06 UTC, merged